# Generated by Django 2.2.5 on 2019-10-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangementmapcomponent',
            name='tree_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
