# Generated by Django 2.2.8 on 2020-03-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_arrangementmapcomponent_tree_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangementmapcomponent',
            name='archivesspace_level',
            field=models.CharField(default='collection', max_length=255),
        ),
    ]
