# Generated by Django 2.2.8 on 2020-06-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_arrangementmapcomponent_archivesspace_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedarrangementmap',
            name='archivesspace_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
