# Generated by Django 3.2.9 on 2021-12-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangementmapcomponent',
            name='child_count',
            field=models.IntegerField(default=0),
        ),
    ]
