version: '3'

services:
  cartographer-db:
    image: postgres:14.4
    environment:
      - POSTGRES_USER=postgres  # name of the application database user
      - POSTGRES_PASSWORD=postgres  # name of the application database user
      - POSTGRES_DB=postgres  # name of the application database
    volumes:
      - cartographerdbvolume:/var/lib/postgresql/data/
  cartographer-backend:
    build: .
    entrypoint: /code/cartographer_backend/entrypoint.sh
    environment:
      - APPLICATION_PORT=${APPLICATION_PORT:-8000}
    volumes:
      - .:/code/cartographer_backend
    ports:
      - "${APPLICATION_PORT:-8000}:${APPLICATION_PORT:-8000}"
    depends_on:
      - cartographer-db

volumes:
  cartographerdbvolume:
